language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default
  global:
    secure: KJuj6wPnkxDbI32sYae8hvskH2z2Np20tZtpXmuV9p3SYSmn4+e91GFv18cTO5vUDjibDRVVgiw83TBJ45Hwy181LOHi6LJNha3K7T4w3pzoZToSzV3YnsVEubLiQk0OyFM3MDHqFQhaZ5eT7GG5i+QHKekvoluPQNwOSY93F/QqRMZzgyLINrzAOYvqrnOxmoiPZJR7PyosZZzYWGns24NcmkbRr9FY0OmcZ3tI85joDYoSPhGSrsd+20FRoqRU7N50y/LQwPay2SeEBy7AS1Rpsq3hw+A32SUsC8sl4DgmUXFyodC9C2JPgxDvLXjK1NZzaWMGhIAYUyZ2cPhfNklx2TkfWtUaRgF1abuqacKeKRR/ouLsLfsUh9dteE+E2gvv1Vg6OHXFiHc2OYmV9Vy7JJumUx+4j5wIZZwkYmPHgqeV6z5fjGKaX2/KaJ7FTt9lnHXNvVbmBbNhExiCuqA7inOxS9seco/44w2zGjzJI19JYvvNMzt6dstoD4pv//MuJnSAO9udxK6vklcUPclOmNqp2RoqtmmXxUZT8g51UtnS8MHtt9RIsSRwRfgBokDWUi9ac57FftD+K4w2vhgBCbspJi1/YkK5pGRraGOkdiS1wTYkI3TEZfQFBTQG6k3Y9nEJLdPP7eDBZ0pR4wYHvQjr7zT7sxZ/52AFk0Q=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g npm@4
- npm --version
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
notifications:
  slack:
    rooms:
      secure: AKgI2qH/dOAPrdFGOVkFiT06dlPYKJZWueje1IHBU/piJ6fGmLwUiB5whAVJoWBjS2vgrxX6oq4KGyghaE5gySiiNQzrLmoK6ky6+pdFLEy62W4bhQq5KzmdHmvzdKovW+FU/wcSbgvGXmkjTCScgtyiHebBAsD3rBc4C6hRU/Upa03GOg8pvLz2OvQH8TLRr4u9xtPcc2K8IjX4gVYBRRND3MsXw4Xn99H8cl4pvuy3xNgV04kZjoY1/cnS6ro2e9oDPh3z3p6u6RNYyYFT2jWMLjedS+GVkX1+l63jj4GBR0QIml1SYVATlsBhWLW+X8bQz4SqwMWDj5I+ZJh9F9U5bUeWi+XBkqYsrnsLNjYuU4P0T2u7z3AQoOB18iQ61D+Qiexk37MxdQSVfSrt0AEkFA1E8aRzAX6tnYdwpPBWFbVsqOGx061AXC2euCbHlVZlMUAbZkFZY/o+ePeDNt2/MNYg2Zp0fe6ficbDVCIQ9fEjzPJ2ruId+UUG/aX5xuwMaOAyUuPJPXZCmECpWiXX0s1PUQk1vtjJIcyvwDd16QQvrZDgVP+k4RfJeYQhBxmI3h9DbQFaCW+rk7C2qGPNPkFG2kiQGfH/gzRgPed6+EN8GYJIkQtLTMkpCqDbd1YwcnsoV73rrb4EWmDP3qErkgmTk95qBEJ6jz27OT8=
